title: Beginner Unity Sushi Cards
hero_image: images/banner.png
description: Make your first game with Unity, a professional game development platform
version: 4.0.0
listed: false
copyedit: false
last_tested: "2018-07-12"
steps:
  - title: Introduction
  - title: What you will need
  - title: Setting the Stage
  - title: Making a Robot
  - title: Adding Colour
  - title: Making the ground
  - title: Making MazeRobo move
  - title: Moving properly
  - title: Camera tracking
  - title: Give MazeRobo something to play with
  - title: Winning!
