title: cd-beginner-unity-sushi
hero_image: images/banner.png
description: cd-beginner-unity-sushi description
version: 4
listed: false
copyedit: false
last_tested: "2018-07-12"
steps:
  - title: Introduction
  - title: What you will need
  - title: Setting the Stage
  - title: Making a Robot
  - title: Adding Colour
  - title: Making the ground
  - title: Making MazeRobo move
  - title: Moving properly
  - title: Camera tracking
  - title: Give MazeRobo something to play with
  - title: Winning!
